rules_folder: rules
run_every:
  seconds: 60

buffer_time:
  minutes: 15

es_host: ${ES_HOST}
es_port: ${ES_PORT}
es_username: ${ES_USERNAME}
es_password: ${ES_PASSWORD}

max_query_size: 1000
max_scrolling_count: 1

writeback_index: psdcloud_elastalert_status
writeback_alias: psdcloud_elastalert_alerts

alert_time_limit:
  days: 2
